- name: Apply kernel network hardening parameters
  ansible.builtin.copy:
    dest: /etc/sysctl.d/99-hardening.conf
    mode: "0644"
    content: |
      net.ipv4.conf.all.accept_redirects=0
      net.ipv4.conf.default.accept_redirects=0
      net.ipv4.conf.all.send_redirects=0
      net.ipv4.conf.default.send_redirects=0
      net.ipv4.conf.all.accept_source_route=0
      net.ipv4.conf.default.accept_source_route=0
      net.ipv4.tcp_syncookies=1
      net.ipv4.conf.all.rp_filter=1
      net.ipv4.conf.default.rp_filter=1
      net.ipv6.conf.all.accept_redirects=0
      net.ipv6.conf.default.accept_redirects=0

- name: Reload sysctl parameters
  ansible.builtin.command: sysctl --system
  changed_when: false
